steps:
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip', '--user']
  - name: 'python:3.9'
    entrypoint: python
    args: ['-m', 'pip', 'install', 'build', 'pytest', 'Flask', '--user']
  # Etapa de Instalacao dependencias
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'appengine/standard_python3/hello_world/requirements.txt', '--user']
  # Etapa de Compilacao
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['appengine/standard_python3/hello_world/main.py', 'sdist', 'bdist_wheel', '--user']
  # Etapa de Teste
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['appengine/standard_python3/hello_world/main_test.py', 'test', '--user']
  # Etapa de Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'appengine/standard_python3/hello_world/app.yaml']